// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StargateAPI.Business.Data;

#nullable disable

namespace StargateAPI.Migrations
{
    [DbContext(typeof(StargateContext))]
    partial class StargateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CareerEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CareerStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentDutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("AstronautDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerEndDate = new DateTime(1971, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CareerStartDate = new DateTime(1962, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Colonel",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            CareerStartDate = new DateTime(1963, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Mission Specialist",
                            CurrentRank = "Colonel",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            CareerStartDate = new DateTime(1978, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Payload Commander",
                            CurrentRank = "Lieutenant",
                            PersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            CareerStartDate = new DateTime(1987, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Science Mission Specialist",
                            CurrentRank = "Lieutenant",
                            PersonId = 4
                        },
                        new
                        {
                            Id = 5,
                            CareerStartDate = new DateTime(1992, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "ISS Commander",
                            CurrentRank = "Colonel",
                            PersonId = 5
                        },
                        new
                        {
                            Id = 6,
                            CareerStartDate = new DateTime(1962, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDutyTitle = "Senior Cosmonaut",
                            CurrentRank = "Major",
                            PersonId = 6
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DutyEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DutyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("AstronautDuty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DutyEndDate = new DateTime(1965, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1962, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot",
                            PersonId = 1,
                            Rank = "2LT"
                        },
                        new
                        {
                            Id = 2,
                            DutyEndDate = new DateTime(1969, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1965, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Flight Commander",
                            PersonId = 1,
                            Rank = "1LT"
                        },
                        new
                        {
                            Id = 3,
                            DutyEndDate = new DateTime(1971, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1969, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Commander",
                            PersonId = 1,
                            Rank = "Colonel"
                        },
                        new
                        {
                            Id = 4,
                            DutyStartDate = new DateTime(1971, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 1,
                            Rank = "Colonel"
                        },
                        new
                        {
                            Id = 5,
                            DutyEndDate = new DateTime(1966, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1963, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot",
                            PersonId = 2,
                            Rank = "2LT"
                        },
                        new
                        {
                            Id = 6,
                            DutyEndDate = new DateTime(1969, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1966, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "LEM Pilot",
                            PersonId = 2,
                            Rank = "Captain"
                        },
                        new
                        {
                            Id = 7,
                            DutyStartDate = new DateTime(1969, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 2,
                            Rank = "Colonel"
                        },
                        new
                        {
                            Id = 8,
                            DutyEndDate = new DateTime(1983, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1978, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 3,
                            Rank = "Ensign"
                        },
                        new
                        {
                            Id = 9,
                            DutyStartDate = new DateTime(1983, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Payload Commander",
                            PersonId = 3,
                            Rank = "Lieutenant"
                        },
                        new
                        {
                            Id = 10,
                            DutyEndDate = new DateTime(1992, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1987, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 4,
                            Rank = "Ensign"
                        },
                        new
                        {
                            Id = 11,
                            DutyStartDate = new DateTime(1992, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Science Mission Specialist",
                            PersonId = 4,
                            Rank = "Lieutenant"
                        },
                        new
                        {
                            Id = 12,
                            DutyEndDate = new DateTime(1995, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1992, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 5,
                            Rank = "2LT"
                        },
                        new
                        {
                            Id = 13,
                            DutyEndDate = new DateTime(2013, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1995, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Mission Specialist",
                            PersonId = 5,
                            Rank = "Captain"
                        },
                        new
                        {
                            Id = 14,
                            DutyStartDate = new DateTime(2013, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "ISS Commander",
                            PersonId = 5,
                            Rank = "Colonel"
                        },
                        new
                        {
                            Id = 15,
                            DutyEndDate = new DateTime(1963, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(1962, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Cosmonaut",
                            PersonId = 6,
                            Rank = "Junior Lieutenant"
                        },
                        new
                        {
                            Id = 16,
                            DutyStartDate = new DateTime(1963, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Senior Cosmonaut",
                            PersonId = 6,
                            Rank = "Major"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsException")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Neil Armstrong",
                            PhotoUrl = "photos/neil-armstrong.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Buzz Aldrin",
                            PhotoUrl = "photos/buzz-aldrin.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sally Ride",
                            PhotoUrl = "photos/sally-ride.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mae Jemison",
                            PhotoUrl = "photos/mae-jemison.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chris Hadfield",
                            PhotoUrl = "photos/chris-hadfield.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Valentina Tereshkova",
                            PhotoUrl = "photos/valentina-tereshkova.jpg"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDetail", b =>
                {
                    b.HasOne("StargateAPI.Business.Data.Person", "Person")
                        .WithOne("AstronautDetail")
                        .HasForeignKey("StargateAPI.Business.Data.AstronautDetail", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.HasOne("StargateAPI.Business.Data.Person", "Person")
                        .WithMany("AstronautDuties")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Navigation("AstronautDetail");

                    b.Navigation("AstronautDuties");
                });
#pragma warning restore 612, 618
        }
    }
}
